- modules/ext-html.xql
Workaround for https://github.com/eXistSolutions/hsg-shell/issues/62
Not sure how to actually repair it, but for sure $target should start with "/" just like all other patterns that come in. Might be a data issue.
now the result looks like:
> Workaround for issue "frus-history research section" #62

- app/scss/_tei.scss
Additional fix:
Apply bootstrap-like cell-spacing and line-height to TEI tables containing class "tei-table1" (which isn't used yet).
> fix(style): Add table-cell padding for default TEI tables #125

- app/scss/_tei.scss
This is a quick fix and should be replaced by a general templating rule
for images concerning their width and height value.
The aim here is to override inline styles coming from the TEI content
file.
Fixes #115
> fix(style): Override wrong hard coded image attributes #115

- app/scss/_tei.scss
- resources/odd/compiled/frus.odd
- resources/odd/source/frus.odd
* Delete width and height for frus-images from odd.
This prevents images from being displayed in wrong ratios, when given incorrect width and height values as inline styles in the TEI.
Fixes #115
* Delete css hotfix for overriding inline image attributes
Reverts previous fix for issue #115
* TODO: Store the images size as metadata and use them to set width and height dynamically, because these attributes are important for valid markup.
> Fix image size

- package.json
When https://www.npmjs.com/package/gulp-exist is updated to at least 1.2.1 merge this PR!
> use gulp-exist v1.2.1 from npm

- app/scss/_customized-bootstrap.scss
- app/scss/_ribbon.scss
- app/scss/_search.scss
- app/scss/_variables.scss
- app/scss/main.scss
- templates/site.html
* Apply style guide compliant colors to navbar
 - refactor navbar styles
- delete obsolete styles
- remove unnecessary margins
- add more space to dropdown-menu items for easier selection on touch
devices
* Reorder z-indices of ribbon and search box , because the ribbon container was lying over the last menu item on certain screen widths, so it couldn’t be selected.
* Delete inline styles from site template
* Set custom bootstrap variables for navbar colors
**Desktop:**
---
**Tablet:**
---
**Mobile:**
---
**In comparison the current navbar on beta view:**
---
> Apply style guide compliant colors to navbar and fix spacing of menu items

- resources/odd/compiled/frus-web.xql
- resources/odd/compiled/frus.css
- resources/odd/compiled/frus.odd
- resources/odd/source/frus.odd
I'm not sure, if I fixed this issue right, because I made my changes in odd lines with containing the tag `<outputRendition>`. Does this tag contain rendition styles, which must be explicitly set here?
What I did is just deleted the style `line-height: 1.3em`, so that the lines are inheriting the correct line-height from the parent-element now.
`resources/odd/source/frus.odd` in line 182:
```
<model predicate="@type = ('participants', 'to', 'from', 'subject')" behaviour="list">
<param name="content">item</param>
<outputRendition>list-style-type: none;</outputRendition>
</model>
```
Fixes #123
> Fix spacing in frus lists #123

- app/scss/_print.scss
- app/scss/main.scss
- pages/departmenthistory/people/person.html
* Hide navigation elements, footer, sidebars, ribbon and breadcrumb
* Reduce font-sizes
* Reduce image sizes
* Display links only as anchor texts marked with underscores
* Hide `<object>` elements
Fixes https://github.com/eXistSolutions/hsg-shell/issues/219
> Add print css

- .gitignore
- build.properties
- build.xml
Adds `local.build.properties` in any path to gitignore.   
Local paths can be declared in `local.build.properties`.
>  Makes editing of build properties possible

- modules/frus-toc-html.xqm
not entirely happy with the solution as there's no ajax call at all but the upside is using back button works as expected; alternative would be commenting out https://github.com/HistoryAtState/hsg-shell/blob/master/resources/scripts/app.js#L118 to prevent double ajax calls but there's still quite a lot of hassle left to make modules/frus-ajax.xql observe start parameters, so not sure it's worth it
> prevent extra ajax call breaking back button behaviour; addresses #273

- modules/rebuild-dates-sort-index.xql
- modules/search.xqm
The new history.state.gov date search interface launched in December 2017 relied on eXist's "sort index" to speed date searches by pre-sorting all documents into chronological order based on the new date metadata. 
This PR replaces our use of the sort index with the new [memsort module](https://github.com/wolfgangmm/memsort), created for us by @wolfgangmm. The improvements are as follows:
1. The memsort module stores its indexes in memory, delivering major performance improvements over the sort module, which stored its index on disk. In our testing and now in production, date searches perform as quickly as plain relevance searches. 
2. The old sort index required us to create two indexes: one for normal chronological order (ascending) and one for reverse chronological order (descending). …
> Migrate from the sort index to the memsort module

- .gitignore
- README.md
- app/templates/site.html
- build.properties
- build.xml
- example.local.build.properties
- expath-pkg.xml
- gulpfile.js
- local.node-exist.json
- modules/open.xql
- modules/rebuild-dates-sort-index.xql
- modules/view.xql
- npm-shrinkwrap.json
- package.json
- pages/about/the-historian.html
* update to node 10.x
* update to latest npm
* add npm package lockfile (npm-shrinkwrap)
* update to gulp 4.x
* update gulpfile to gulp 4 syntax
* remove node-exist json code from gulpfile into separate file
* add example file for creating a local.build.properties file
* update build.properties: remove node@6 reference from the npm path,
but leave the specified node.PATH hard coded for the time being (from
my pov, we could remove the node-version dependency here, it will be
checked in the „engine“ field in package.json)
* update readme with a comprehensive installation and update
description (todo: Update the Prerequisites section about „homebrew“).
Adresses https://github.com/HistoryAtState/hsg-project/issues/48
> breaking: Update build tools and dependencies

- controller.xql
With the latest fixes to the web tests I discovered that the endpoint for "departmenthistory/" was not working as in my local tests before, so I added it now.
PR https://github.com/HistoryAtState/hsg-shell/pull/356 is relying on this fix, otherwise the new test will fail when opening page `departmenthistory/`.
> fix(controller): Add endpoint for "departmenthistory" landing

- controller.xql
- tests/specs/replication/replication.spec.js
- tests/xquery/validate-replication.xq
- wdio.conf.js
The test creates an xml file containing the current date time, which gets stored on backend1. A second after the file was created the tests verifies if the xml file with the same datetime value is present on backend2 as well.
> added replication test

- package-lock.json
- package.json
CI test server Jenkins is currently testing on headless Chrome v86
and is expecting Chromedriver v86.0.0 to be running in the test code.
This feature branch will be needed for new Jenkins server configuration in job `hsg-prod-1991-webtests`.
**Stays WIP until we entirely switch to the new HSG servers.**
> (WIP) fix(webtest): Update Chromedriver to v86.0.0

- app/scss/_miscellaneous.scss
Before, the footnotes for https://history.state.gov/historicaldocuments/frus1919Russia/d275 appeared as follows:
> <img width="624" alt="Screen Shot 2021-12-02 at 11 38 06 AM" src="https://user-images.githubusercontent.com/59118/144464313-1a9274f6-a28d-4f3f-ac85-29a0a530e646.png">
The source TEI for the middle footnote's label was `n="60a"`, and hsg-shell's frus.odd faithfully translated this value into the HTML `li/@value` attribute. So, why is the "a" truncated from "60a" when we view the document above? According to the [HTML specs for `li/@value`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li#attributes):
> The only allowed value for this attribute is a number, even if the list is displayed with Roman numerals or letters. 
Browsers take the leading numbers and chop off …
> Fix display of footnote labels with non-numeric parts

- modules/frus-toc-html.xqm
As reported in #391, inner TOC views were displaying footnotes. 
Before this PR, the TOC at https://history.state.gov/historicaldocuments/frus1941v06/comp1 shows footnotes on the child chapter divs:
> <img width="590" alt="Screen Shot 2021-12-02 at 12 27 43 PM" src="https://user-images.githubusercontent.com/59118/144472828-7a8a6e81-1846-433d-8a44-6367018a416e.png">
With this PR, the footnotes are suppressed:
> <img width="591" alt="Screen Shot 2021-12-02 at 12 27 54 PM" src="https://user-images.githubusercontent.com/59118/144472869-4d6ba226-b88f-4632-8f24-1bc850d01135.png">
> Ensure footnotes are suppressed from "inner" TOC views

- controller.xql
Replication tests use this URI to trigger a replication event.
If the response to this URI is cached anywhere, the replication event might not get triggered.
This leads to wrongly failing replication tests.
This PR ensure results of 'validate-replication' are never cached.
> Ensure results of 'validate-replication' are never cached

- modules/pocom-html.xqm
- pages/departmenthistory/people/principals-chiefs.xml
See https://github.com/HistoryAtState/pocom/issues/29
@joshbotts If you send me the text to be added to ["Dates of Service"](https://history.state.gov/departmenthistory/people/principals-chiefs#dates-of-service) on the POCOM landing page, I can fold it into the [the HTML template](https://github.com/HistoryAtState/hsg-shell/blob/master/pages/departmenthistory/people/principals-chiefs.xml) and include it in this PR.
e.g., http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/popp-william-w
**Before**
> <img width="510" alt="Screen Shot 2022-02-05 at 11 39 40 AM" src="https://user-images.githubusercontent.com/59118/152652218-2a94a658-827e-4e49-a1fa-531742f39b46.png">
**After**
> <img width="512" alt="Screen Shot 2022-02-05 at 11 40 03 AM" …
> Implement COM "arrived" structure

- modules/frus-ajax.xql
This PR extends https://github.com/HistoryAtState/hsg-shell/pull/396 to previous & next navigation buttons on TEI resources. 
Requests to the frus-ajax.xql endpoint will now:
- Return Created and Last-Modified response headers
- Handle a If-Modified-Since request header, returning a 304 Not Modified status if appropriate
The PR also adds comments explaining how the `url` request parameter maps onto publication resource identifiers and changes variable names to conform to the conventions used in pages.xqm and config.xqm.
> Extend Last-Modified and If-Modified-Since to prev/next Ajax requests

- app/templates/site.xml
This open source contribution to the HSG-Shell project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.
> Fix broken ant task `xmlvalidate` caused by empty html attribute in main page template

- modules/fo.xql
This open source contribution to the `hsg-shell` project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.
> fix(module): Delete obsolete tei-simple dependency

- resources/scripts/app.js
The current IIIF Cantaloupe server has version 4.1.11, but the development settings have been made for Cantaloupe 5, which supports the lastest IIIF Image API 3. Cantaloupe 4x only supports up to IIIF Image API 2, therefore switched back to 2 (https://cantaloupe-project.github.io/manual/4.1/endpoints.html).
---
This open source contribution to the `hsg-shell` project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.
> fix(app.js): Switch OSD settings from local IIIF server to production

- .github/dependabot.yml
- .github/workflows/build.yml
- .gitignore
- .releaserc
- README.md
- build.properties.xml
- build.xml
- commitlint.config.cjs
- package-lock.json
- package.json
- tests/bats/smoke-test.bats
Automate releases via CI
add smoke test 
strict linting rules
@joewiz I m not sure what to make of the files failing well-formedness checks in `tests/data/sitemap-config/`. Should they be:
- removed,
- ignored,
- or fixed
> Feat automate build

- app/templates/site.xml
- controller.xql
- modules/config.xqm
- modules/frus-history-html.xqm
- modules/pages.xqm
- modules/search.xqm
- pages/historicaldocuments/frus-history/research/article.xml
- urls.xml
See https://github.com/HistoryAtState/hsg-shell/issues/349.
> Add Administrative Timeline, FRUS History collections to search

- modules/config.xqm
The error could be seen on pages like https://history.state.gov/historicaldocuments/frus-history/documents/1959-11-06-hac-meeting-minutes (and others linked from the `documents` parent slug) and indicated that the expected `document-last-modified` function in `$config:PUBLICATIONS` was missing. This PR adds this function to the `frus-history-documents` entry. (A `document-last-modified` or `section-last-modified` function is only expected (a) when `pages:load` is called and (b) when there's both a `$publication-id` and `$document-id` parameter.)
```text
err:XPTY0004 Expected exactly one item for the function to be called, got 0. Expression: map:get($config:PUBLICATIONS, untyped-value-check[xs:anyAtomicType, $publication-id])?document-last-modified [at line 145, column 55, source: …
```
> Fix last-modified error on frus-history (sesqui) document pages

- modules/ext-html.xql
We see a lot of crawlers hitting FRUS page image pages. Since these pages have no text content, search engines needn't index these pages. This doesn't prevent anyone from visiting these pages; it just advises bots that they shouldn't follow links to these pages. Hopefully it'll prevent some unnecessary traffic to a very large collection of pages (~ half a million).
> Advise crawlers not to follow pb links

- modules/config.xqm
> Cache additional routes: people/by-year and people/by-name

- resources/scripts/app.js
The deprecated size() method was removed in jQuery 3. Read the length property of the returned array instead.
For readability the function with the misleading name allSelectedButDocuments was renamed to onlyHistoricalDocumentsSelected and simplified.
> fix(app.js): use of removed size() method

- controller.xql
- repo.xml
Instead of ignoring multiple slashes, redirect requests containing multiple adjacent slashes to the URL with only one.
Now, this URL:
https://history.state.gov///////////////historicaldocuments/frus1901/d1
... will be redirected to:
https://history.state.gov/historicaldocuments/frus1901/d1
(They were ignored because we determined the slugs in a path (`$path-parts`) using the expression `tokenize($exist:path, "/")[. ne ""]`. That's fine, but the side effect was serving up resources at unexpected/non-canonical paths.)
> Redirect requests with multiple slashes

- modules/config.xqm
- repo.xml
… for about-frus and citing-frus page templates, since they have no dependencies on the FRUS collection and should be treated as having been updated whenever hsg-shell is updated
> Calculate last-modified dates from hsg-shell

- app/templates/site.xml
- pages/about/contact-us.xml
- repo.xml
Via Alina, “We don't have a fax machine anymore so the number can be deleted.”
> Remove fax number from OH contact info
