modules/ext-html.xql, modules/pages.xql, modules/toc.xql, resources/css/style.css, resources/css/style.less, resources/odd/compiled/frus-web.xql, resources/odd/compiled/frus.css, resources/odd/compiled/frus.odd, resources/odd/source/frus.odd
special focus on:
- headings
- footnotes
- document lists
- lists
=> Steps toward ODD parity with FRUS

expath-pkg.xml
but package manager responds with an error when installing this. @wolfgangmm - do you have any idea why?
=> declare dependency on tei-simple package

modules/pocom-html.xqm
=> fix for https://github.com/eXistSolutions/hsg-shell/issues/84

modules/pocom-html.xqm
suggestion for https://github.com/eXistSolutions/hsg-shell/issues/83
=> Bootstrap-ify Alpha listing officers

modules/app.xqm, modules/education-html.xqm
Proposed fix for https://github.com/eXistSolutions/hsg-shell/issues/59
=> Fix links to http://s3.amazonaws.com/static.history.state.gov

app/scss/_customized-bootstrap.scss
=> fix(style): Apply original bootstrap table styles #125

modules/frus-history-html.xqm, modules/milestones-html.xqm, modules/pages.xqm, modules/pocom-html.xqm, modules/tags-html.xqm, pages/departmenthistory/people/by-name/letter.html, pages/departmenthistory/people/by-year/year.html, pages/departmenthistory/people/chiefsofmission/by-role-or-country-id.html, pages/departmenthistory/people/person.html, pages/departmenthistory/people/principalofficers/by-role-id.html, pages/education/module.html, pages/historicaldocuments/frus-history/documents/document.html, pages/historicaldocuments/frus-history/monograph-interior.html, pages/historicaldocuments/frus-history/research/article.html, pages/historicaldocuments/volume-interior.html, pages/milestones/chapter/article.html, pages/milestones/chapter/index.html, pages/tags/browse.html
@joewiz Have a look at the pages mentioned in #60 and  the outcome.
You might also want to review the implementation and look for possible pitfalls.
There is definitely the need to further abstract the breadcrumb creation into a separate module.
But let us leave that for later.
=> Create breadcrumbs  for different dynamic sections of the content - closes #60

modules/pages.xqm
Fixes https://github.com/eXistSolutions/hsg-shell/issues/216
=> Show rewrite notice for any pending document #216

modules/frus-html.xqm, pages/historicaldocuments/volume-interior.html, pages/historicaldocuments/volume-landing.html
Only show 
* search when TEI:text is available and 
* download panels when pdf/ebooks available
Fixes https://github.com/eXistSolutions/hsg-shell/issues/208
=> Hide elements if no data is available #208

app/templates/site.html, gulpfile.js
=> fix production JS

modules/pocom-html.xqm
- Add support for “circa” dates
- Improve code for constructing name and birth/death date strings
- Show no career type information for "pre-1915" folks
=> Align with pocom data

modules/pages.xqm
awaiting feedback from @wolfgangmm
=> WIP: Proposed fix to #257

app/templates/site.html, build.xml, modules/config.xqm, modules/ext-html.xql, modules/frus-history-html.xqm, modules/travels-html.xqm, modules/visits-html.xqm, pages/milestones/all.html, pages/milestones/chapter/article.html, pages/milestones/chapter/index.html, pages/milestones/index.html, resources/robots.txt
Closes https://github.com/HistoryAtState/hsg-shell/issues/276
=> Reorganize menu bar, retire milestones

pages/search/_submit-search-button.html, pages/search/search-landing.html, resources/scripts/app.js
* Replace (< IE9) unsupported addEventListener() with JQuery
$(document).on
* Add polyfill for unsupported padStar() / padEvent()
(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart)
* Comment-out debug logs
=> Fixes for IE bugs #325

resources/scripts/app.js
=> Preserve browser history in search actions #315

tests/xquery/validate-results-of-twitter-jobs.xq
this PR is needed to fix the daily Jenkins tests
=> adjusted twitter-cronjob tests to work with different cron-job syntax

pages/departmenthistory/short-history/index.xml, pages/departmenthistory/short-history/section.xml
=> Fix short-history interior pgs link to landing pg

package-lock.json, package.json
Update package.json and package-lock.json after security audit.
=> chore(test): Update ChromeDriver to v91.0.1

pages/departmenthistory/timeline/index.xml, pages/departmenthistory/timeline/section.xml
this update is required once administrative-timeline events from 2020 and newer shall be displayed in hsg-shell/departmenthistory/timeline
=> added decade '2020 - present'

build.properties.xml, expath-pkg.xml.tmpl
This open source contribution to the `hsg-shell` project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.
=> Fix version and dependency

controller.xql, pages/historicaldocuments/index.xml, urls.xml, wdio.conf.js
=> Pull back volume titles facility

.releaserc
=> fix(xar): make prod default

pages/milestones/all.xml, pages/milestones/chapter/index.xml, pages/milestones/index.xml
=> Remove duplicate sidebar entries in Milestones pages

modules/link.xqm
suppress the /exist/apps/hsg-shell slugs from the referenced URLs for error reports
=> fix: adjusted uri in link:report-issue-body

app/scss/_tei.scss
... by applying the same definition used for persons lists
=> Fix sources list indentation

resources/odd/source/configuration.xml, resources/odd/source/elementsummary.xml, resources/odd/source/headerelements.xml, resources/odd/source/headeronly.xml, resources/odd/source/simpleelements.xml, resources/opensearch.xml
See https://github.com/HistoryAtState/hsg-project/commit/b6bbe466f513ce888db7725e433d311b80047142
=> Remove BOM characters

pages/departmenthistory/timeline/index.xml
See https://github.com/HistoryAtState/administrative-timeline/pull/13
=> Sync admin timeline intro with data repo

controller.xql, modules/config.xqm
implementing last-modified for all possible routes through the controller
=> feat: added publication-id to every route in controller

modules/config.xqm, modules/visits-html.xqm, pages/departmenthistory/visits/index.xml, repo.xml
- Add introduction to Visits
- Draw country IDs and names exclusively from DOA
=> Prepare for 2024 Visits

modules/config.xqm, modules/travels-html.xqm, pages/departmenthistory/travels/president/index.xml, pages/departmenthistory/travels/secretary/index.xml, repo.xml
- Add introduction to Travels
- Draw country IDs and names exclusively from DOA
=> Prepare for 2024 Travels

controller.xql, modules/config.xqm, modules/travels-html.xqm, modules/visits-html.xqm, repo.xml
In preparation for change of Tillerson's ID in Travels
=> Redirect secretary travels requests for secretary's old-id to new-id

controller.xql, modules/pocom-html.xqm, repo.xml
See also #509 for Secretary Travels.
=> Redirect POCOM requests for persons' old-ids to new-id
